name = "CassetteOverlay"
uuid = "d78b62d4-37fa-4a6f-acd8-2f19986eb9ee"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.1.11"

[compat]
julia = "1.10"

[extras]
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NaNMath"]
