name = "CassetteOverlay"
uuid = "d78b62d4-37fa-4a6f-acd8-2f19986eb9ee"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]
version = "0.0.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
