name = "CassetteBase"
uuid = "6dd3e646-b1c5-42c7-94be-00277fa12e22"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]
version = "0.2.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
